//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public string Article { get; set; }
        public string Author { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public System.DateTime PublishingYear { get; set; }
        public int Status { get; set; }
        public string Image { get; set; }
    
        public virtual BookStatuses BookStatuses { get; set; }
    }
}
