//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookGenres
    {
        public string IDBook { get; set; }
        public int IDGenre { get; set; }
        public Nullable<int> Popularity { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Genres Genres { get; set; }
    }
}
