
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BookStats.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Genres
{

    public Genres()
    {

        this.BookGenres = new HashSet<BookGenres>();

    }


    public int ID { get; set; }

    public string GenreName { get; set; }



    public virtual ICollection<BookGenres> BookGenres { get; set; }

}

}
