
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BookStats.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ReadingLists
{

    public ReadingLists()
    {

        this.ReadingListBooks = new HashSet<ReadingListBooks>();

    }


    public int ID { get; set; }

    public int UserID { get; set; }

    public string TableSource { get; set; }



    public virtual ICollection<ReadingListBooks> ReadingListBooks { get; set; }

    public virtual Users Users { get; set; }

}

}
